- name: Query all tenants
  hosts: apic
  connection: local
  gather_facts: no
   
  tasks:
    - name: Add a new tenant
      aci_tenant:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: Ansible_Test
        description: Tenant created using Ansible
        validate_certs: no
        state: present 
    - name: Add a new AP
      aci_ap:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: Ansible_Test
        ap: default
        description: default ap
        state: present   
        validate_certs: no
    - name: Add Bridge Domain
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        state: present
        tenant: Ansible_Test
        bd: Ansible_Bd
        vrf: vrf_lab
        arp_flooding: yes
        l2_unknown_unicast: flood
    - name: Add Bridge Domain2
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        state: present
        tenant: Ansible_Test
        bd: Ansible_Bd_app
        vrf: vrf_lab
        arp_flooding: yes
        l2_unknown_unicast: flood
    - name: Add Bridge Domain3
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        state: present
        tenant: Ansible_Test
        bd: Ansible_Bd_web
        vrf: vrf_lab
        arp_flooding: yes
        l2_unknown_unicast: flood
    - name: Add Bridge Domain4
      aci_bd:
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        state: present
        tenant: Ansible_Test
        bd: Ansible_Bd_db
        vrf: vrf_lab
        arp_flooding: yes
        l2_unknown_unicast: flood         
    - name : Create a subnet
      aci_bd_subnet:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: Ansible_Test
        bd: Ansible_Bd
        gateway: 10.1.1.1
        mask: 24
        state: present
        validate_certs: no 
    - name : Add a new EPG
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: Ansible_Test
        ap: default
        bd: Ansible_Bd
        epg: web_epg
        description: web_intranet_epg
        validate_certs: no
    - name : Add a new EPG2
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: Ansible_Test
        ap: default
        bd: Ansible_Bd
        epg: app_epg
        description: web_intranet_epg
        validate_certs: no
    - name : Add a new EPG3
      aci_epg:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: Ansible_Test
        ap: default
        bd: Ansible_Bd
        epg: db_epg
        description: web_intranet_epg
        validate_certs: no        
    - name : Create static routes
      aci_l3out:
        hostname: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        tenant: Ansible_Test
        l3out: l3out
        logical_node: nodeName
        node_id: 101
        pod_id: 1
        prefix: 10.10.0.0/16
        vrf: vrf_lab
        domain: l3dom_prod
        delegate_to: localhost     